## Session #1 Homework


### Set up the environment

You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from
[06-environment.md](https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/06-environment.md).






## Submit the results

* Submit your results here: https://forms.gle/vLp3mvtnrjJxCZx66
* You can submit your solution multiple times. In this case, only the last submission will be used 
* If your answer doesn't match options exactly, select the closest one


## Deadline

The deadline for submitting is 12 September 2022 (Monday), 23:00 CEST (Berlin time).

After that, the form will be closed.



### Question 1

What's the version of NumPy that you installed? 

You can get the version information using the `__version__` field:

```python
np.__version__
```

In [2]:
import numpy as np

np.__version__

'1.21.5'

### Getting the data 

For this homework, we'll use the Car price dataset. Download it from 
[here](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv).

You can do it with wget:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
```

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

### Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

- 16
- 6572
- 11914
- 18990

In [101]:
import pandas as pd

cars_df = pd.read_csv("data.csv")

In [8]:
cars_df.index

RangeIndex(start=0, stop=11914, step=1)

In [9]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

### Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

- Chevrolet, Volkswagen, Toyota
- Chevrolet, Ford, Toyota
- Ford, Volkswagen, Toyota
- Chevrolet, Ford, Volkswagen

> **Note**: You should rely on "Make" column in this question.

In [11]:
cars_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [18]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

### ALERT: This question is not correct in Form.

In [143]:
cars_df.groupby("Make").count().sort_values(by="Model", ascending=False)

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                        
Chevrolet       1123  1123              1123       1117              1123   
Ford             881   881               881        868               881   
Volkswagen       809   809               809        809               809   
Toyota           746   746               746        744               746   
Dodge            626   626               626        626               626   
Nissan           558   558               558        548               558   
GMC              515   515               515        515               515   
Honda            449   449               449        447               449   
Mazda            423   423               423        423               423   
Cadillac         397   397               397        397               397   
Mercedes-Benz    353   353               353        352               353   
Suzuki           351   351               348        351               351   
BMW              334   334               334        334               334   
Infiniti         330   330               330        330               330   
Audi             328   328               328        328               328   
Hyundai          303   303               303        303               303   
Volvo            281   281               281        281               281   
Subaru           256   256               256        256               256   
Acura            252   252               252        252               252   
Kia              231   231               231        226               231   
Mitsubishi       213   213               213        212               213   
Lexus            202   202               202        202               202   
Buick            196   196               196        196               196   
Chrysler         187   187               187        187               187   
Pontiac          186   186               186        186               186   
Lincoln          164   164               164        156               164   
Oldsmobile       150   150               150        150               150   
Land Rover       143   143               143        143               143   
Porsche          136   136               136        136               136   
Saab             111   111               111        111               111   
Aston Martin      93    93                93         93                93   
Plymouth          82    82                82         82                82   
Bentley           74    74                74         74                74   
Ferrari           69    69                69         69                69   
FIAT              62    62                62         59                62   
Scion             60    60                60         60                60   
Maserati          58    58                58         58                58   
Lamborghini       52    52                52         52                52   
Rolls-Royce       31    31                31         31                31   
Lotus             29    29                29         29                29   
Tesla             18    18                18          0                18   
HUMMER            17    17                17         17                17   
Maybach           16    16                16         16                16   
McLaren            5     5                 5          5                 5   
Alfa Romeo         5     5                 5          5                 5   
Spyker             3     3                 3          3                 3   
Bugatti            3     3                 3          3                 3   
Genesis            3     3                 3          3                 3   

               Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                               
Chevrolet                   

In [44]:
cars_df[["Make", "Popularity", "Model"]].groupby("Make").count().sort_values(by='Model', ascending=False)

Popularity  Model
Make                            
Chevrolet            1123   1123
Ford                  881    881
Volkswagen            809    809
Toyota                746    746
Dodge                 626    626
Nissan                558    558
GMC                   515    515
Honda                 449    449
Mazda                 423    423
Cadillac              397    397
Mercedes-Benz         353    353
Suzuki                351    351
BMW                   334    334
Infiniti              330    330
Audi                  328    328
Hyundai               303    303
Volvo                 281    281
Subaru                256    256
Acura                 252    252
Kia                   231    231
Mitsubishi            213    213
Lexus                 202    202
Buick                 196    196
Chrysler              187    187
Pontiac               186    186
Lincoln               164    164
Oldsmobile            150    150
Land Rover            143    143
Porsche               136    136
Saab                  111    111
Aston Martin           93     93
Plymouth               82     82
Bentley                74     74
Ferrari                69     69
FIAT                   62     62
Scion                  60     60
Maserati               58     58
Lamborghini            52     52
Rolls-Royce            31     31
Lotus                  29     29
Tesla                  18     18
HUMMER                 17     17
Maybach                16     16
McLaren                 5      5
Alfa Romeo              5      5
Spyker                  3      3
Bugatti                 3      3
Genesis                 3      3

### Question 4

What's the number of unique Audi car models in the dataset?

- 3
- 16
- 26
- 34

In [50]:
cars_df["Make"].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [102]:
audi_cars_df = cars_df[cars_df["Make"] == "Audi"]
audi_cars_df.Model.nunique()

34

### Question 5

How many columns in the dataset have missing values?

- 5
- 6
- 7
- 8

In [62]:
cars_df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### Question 6

1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

> Hint: refer to existing `mode` and `median` functions to complete the task.

- Yes
- No

In [103]:
eng_cy_med = cars_df["Engine Cylinders"].median()
eng_cy_med

6.0

In [107]:
cars_df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [108]:
most_freq_cy = cars_df[["Engine Cylinders", "Model"]].groupby(["Engine Cylinders"]).count().sort_values("Model", ascending=False).index[0]
most_freq_cy

4.0

In [144]:
cars_df.mode()

Make           Model  Year  Engine Fuel Type  Engine HP  \
0  Chevrolet  Silverado 1500  2015  regular unleaded      200.0   

   Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0               4.0         AUTOMATIC  front wheel drive              4.0   

  Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
0       Crossover      Compact         Sedan           24        17   

   Popularity  MSRP  
0        1385  2000

In [109]:
cars_df["Engine Cylinders"] = cars_df["Engine Cylinders"].fillna(value=most_freq_cy)

In [111]:
cars_df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [110]:
eng_cy_med2 = cars_df["Engine Cylinders"].median()
eng_cy_med2

6.0

In [113]:
eng_cy_med != eng_cy_med2

False

### Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Compute the inverse of `XTX`.
7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the value of the first element of `w`?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- -0.0723
- 4.5949
- 31.6537
- 63.5643

In [116]:
lotus_cars_df = cars_df[cars_df["Make"] == "Lotus"]
lotus_cars_df.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [118]:
lotus_cars_df = lotus_cars_df[["Engine HP", "Engine Cylinders"]]
lotus_cars_df.describe()

Engine HP  Engine Cylinders
count   29.000000         29.000000
mean   275.965517          5.241379
std     64.131830          1.353703
min    189.000000          4.000000
25%    218.000000          4.000000
50%    276.000000          6.000000
75%    345.000000          6.000000
max    400.000000          8.000000

In [121]:
lotus_cars_df = lotus_cars_df.drop_duplicates()
lotus_cars_df.describe()

Engine HP  Engine Cylinders
count    9.000000          9.000000
mean   276.888889          5.111111
std     72.177636          1.452966
min    189.000000          4.000000
25%    218.000000          4.000000
50%    257.000000          4.000000
75%    345.000000          6.000000
max    400.000000          8.000000

In [122]:
X = lotus_cars_df.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [125]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [126]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [131]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [132]:
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

## Submit the results