In [2]:
import numpy as np

## Vector-vector multiplication (dot product)

In [4]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [5]:
u * v

array([ 2,  0,  0, 12])

In [6]:
u.shape

(4,)

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [10]:
vector_vector_multiplication(u, v)

14.0

In [11]:
u.dot(v)

14

## Matrix-Vector Multiplication

In [14]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 4, 5, 6]
])
v = np.array([1, 2, 0, 5])

In [15]:
U.shape

(3, 4)

In [18]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    res_rows = U.shape[0]
    
    result = np.zeros(res_rows)
    
    for i in range(res_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [19]:
matrix_vector_multiplication(U, v)

array([40., 15., 41.])

In [20]:
U.dot(v)

array([40, 15, 41])

## Matrix-matrix multiplication

In [57]:
U = np.random.randint(low=0, high=10, size=(3, 4))
V = np.random.randint(low=0, high=5, size=[4, 3])

print(U, '\n\n', V)

[[8 1 2 9]
 [0 6 1 5]
 [5 4 1 7]] 

 [[0 3 3]
 [2 1 0]
 [1 0 4]
 [1 0 4]]


In [31]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [32]:
matrix_matrix_multiplication(U, V)

array([[ 4095.,  3816.,  9965.],
       [ 4902.,  6387., 12191.],
       [ 7630.,  8831., 20987.]])

In [33]:
U.dot(V)

array([[ 4095,  3816,  9965],
       [ 4902,  6387, 12191],
       [ 7630,  8831, 20987]])

## Identity Matrix

In [35]:
I = np.eye(3)

In [36]:
V

array([[41,  4, 87],
       [40, 41, 95],
       [10, 23, 63],
       [ 9, 36, 23]])

In [37]:
V.dot(I)

array([[41.,  4., 87.],
       [40., 41., 95.],
       [10., 23., 63.],
       [ 9., 36., 23.]])

## Matrix Inverse

In [58]:
Vs = V[[0, 1, 2]]
Vs

array([[0, 3, 3],
       [2, 1, 0],
       [1, 0, 4]])

In [59]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-0.14814815,  0.44444444,  0.11111111],
       [ 0.2962963 ,  0.11111111, -0.22222222],
       [ 0.03703704, -0.11111111,  0.22222222]])

In [60]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])