In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
import random
np.full(10, random.random())

array([0.2122639, 0.2122639, 0.2122639, 0.2122639, 0.2122639, 0.2122639,
       0.2122639, 0.2122639, 0.2122639, 0.2122639])

In [5]:
a = np.array([1, 2, 3, 5, 7, 12])

In [6]:
a[2] = 10

In [7]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays

In [30]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [34]:
n[0, 1] = 20

In [35]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [40]:
n[2] = [3, 4, 5]

In [41]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 3,  4,  5]])

In [43]:
n[:, 1] = [6, 8, 9]

In [44]:
n

array([[1, 6, 3],
       [4, 8, 6],
       [3, 9, 5]])

# Random arrays

In [49]:
# for a fixed set of random numbers generated everytime
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [56]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [58]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise Operations

In [59]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
a + 1

array([1, 2, 3, 4, 5])

In [62]:
a * 2

array([0, 2, 4, 6, 8])

In [74]:
b = (10 + (a * 2)) ** 2 / 100

In [68]:
a + b

array([ 90, 135, 188, 249, 318])

# Comparison operations

In [69]:
a

array([0, 1, 2, 3, 4])

In [70]:
a > 2

array([False, False, False,  True,  True])

In [75]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [76]:
a > b

array([False, False,  True,  True,  True])

In [77]:
a[a > b]

array([2, 3, 4])

# Summarizing Operations

In [78]:
a

array([0, 1, 2, 3, 4])

In [79]:
a.min()

0

In [80]:
a.max()

4

In [81]:
a.sum()

10

In [82]:
a.mean()

2.0

In [83]:
a.std()

1.4142135623730951